import type { Metadata } from "next";
import { Geist, Geist_Mono, Lora } from "next/font/google";
import "./globals.css";
import { AlertTriangle } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wei Chen - Portfolio",
  description: "Personal portfolio of Wei Chen, Engineering Leader at YouTube.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lora.variable} antialiased selection:bg-[#bc1a22] selection:text-white`}
      >
        <div className="relative">
          {/* AI Experiment Banner */}
          <div className="bg-amber-100 border-b border-amber-200 py-3 px-6 relative z-[100] transition-colors duration-500">
            <div className="max-w-6xl mx-auto flex items-center justify-center gap-3 text-center">
              <AlertTriangle className="w-5 h-5 text-amber-700 shrink-0" />
              <p className="text-sm font-bold tracking-tight text-amber-900 leading-tight">
                AI Experiment: This portfolio was generated by an AI assistant for demonstration. Content is not fully validated and may contain errors.
              </p>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
